version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
        - docker build -t jzhao5/docker-react2 -f Dockerfile.dev .
        - docker run jzhao5/docker-react2 npm run test
  post_build:
    commands:
        - echo Build completed on `date`
        - mv target/app.zip app.zip

artifacts:
  files:
    - .ebextensions/*
    - app.zip
