version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
        - docker build -t jzhao5/docker-react2 .
  post_build:
    commands:
        - echo Build completed on `date`
        - aws s3 copy /app s3://myapp-demo-2020/ . --recursive
