version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  build:
    commands:
        - docker build -t jzhao5/docker-react2 -f Dockerfile.dev .
  post_build:
    commands:
        - echo Build completed on `date`
        - aws s3 sync ./app $S3_BUCKET 
